# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET TentaclePing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, ubuntu-24.04-arm]
            include:
                - os: ubuntu-latest
                  runtime: linux-x64
                - os: windows-latest
                  runtime: win-x64
                - os: ubuntu-24.04-arm
                  runtime: linux-arm64
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Publish Self-Contained
      run: dotnet publish -c Release -r ${{ matrix.runtime }} --self-contained

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tentacleping-${{ matrix.runtime }}-dotnet
        path: source/*/bin/Release/*/publish/