# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET TentaclePing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, ubuntu-24.04-arm]
            include:
                - os: ubuntu-latest
                  runtime: linux-x64
                - os: windows-latest
                  runtime: win-x64
                - os: ubuntu-24.04-arm
                  runtime: linux-arm64
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore source/

    - name: Build
      run: dotnet build source/ --no-restore -c Release

    - name: Publish Self-Contained
      run: dotnet publish source/ -c Release -r ${{ matrix.runtime }} --self-contained -o publish/

    - name: Organize Published Files
      run: |
        # Create a flat structure for archiving
        mkdir -p dist
        cp publish/TentaclePing/TentaclePing* dist/ 2>/dev/null || true
        cp publish/TentaclePong/TentaclePong* dist/ 2>/dev/null || true
        ls -la dist/
      
    - name: Create Archive (Linux)
      if: runner.os != 'Windows'
      run: |
        tar -czf TentaclePing-${{ matrix.runtime }}.tar.gz -C dist .
        
    - name: Create Archive (Windows)  
      if: runner.os == 'Windows'
      run: |
        Compress-Archive -Path dist\* -DestinationPath TentaclePing-${{ matrix.runtime }}.zip

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TentaclePing-${{ matrix.runtime }}
        path: |
          TentaclePing-${{ matrix.runtime }}.tar.gz
          TentaclePing-${{ matrix.runtime }}.zip

